#!/bin/bash
# GitHub Pages Deployment Script
# Generated by Shiny App Publisher

echo 'Setting up Git configuration for GitHub Pages...'
git config --global user.name 'GitHub Actions'
git config --global user.email 'actions@github.com'

echo 'Creating and switching to gh-pages branch...'
git checkout --orphan gh-pages

echo 'Removing existing files...'
git rm -rf .

echo 'Creating GitHub Pages content...'
cat > index.html << 'EOF'
<!DOCTYPE html>
<html>
<head>
    <title>regression_modeling_app</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
        body { font-family: Arial, sans-serif; margin: 40px; }
        .container { max-width: 800px; margin: 0 auto; }
        h1 { color: #333; }
        .card { border: 1px solid #ddd; padding: 20px; margin: 20px 0; border-radius: 5px; }
    </style>
</head>
<body>
    <div class="container">
        <h1>regression_modeling_app</h1>
        <p>A Shiny Healthcare Analytics Dashboard Using  Simulated Healthcare Data for Linear Regression</p>
        
        <div class="card">
            <h2>Shiny Application</h2>
            <p>This application is deployed using GitHub Actions and GitHub Pages.</p>
            <p>Repository: <a href="https://github.com/Kiplagatnoel/regression_modeling_app">https://github.com/Kiplagatnoel/regression_modeling_app</a></p>
        </div>
    </div>
</body>
</html>
EOF

echo 'Disabling Jekyll...'
touch .nojekyll

echo 'Staging files...'
git add -A

echo 'Committing changes...'
git commit -m "Deploy to GitHub Pages: $(date +'%Y-%m-%d %H:%M:%S')"

echo 'Pushing to GitHub...'
git push origin gh-pages --force

echo 'GitHub Pages deployment completed!'
echo 'Your site will be available at: https://Kiplagatnoel.github.io/regression_modeling_app/'

